blank_issues_enabled: false
contact_links:
  - name: issue template
    url: https://github.com/FlawDetector-team-yes/FlawDetector-team-yes/blob/dev/.github/ISSUE_TEMPLATE/issue_template.md
    about: Please ask and answer questions here.

